name: Context-workflow
on: workflow_dispatcher

jobs:
    context-job:
        runs-on: ubuntu-latest
        steps:
            - name: output github context
              run: echo "${{ toJson(github)}}" 


